# This file was generated by GoReleaser. DO NOT EDIT.
cask "oku" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "b1afc2fbf5bea366268ceef3cb2c925e9bbd056b48c3c0ea6a47ef2465959375"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed4d1db05a565ef40336544a0d8aadf9e82e316b8314640941b8aba138ff89d8"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "695674bb157acafcd1b92643b22083b2f86cf86b9e06ca9286d1093098e287dd"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44cd86bdf19d45c5ba0e7f1a8a58e555bbe51853d2acc77da5dec3dc85ebec6d"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_linux_arm64.tar.gz"
    end
  end

  name "oku"
  desc "A terminal companion for Hardcover — track your reading from the CLI"
  homepage "https://github.com/Kameleon21/oku"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oku"

  # No zap stanza required

end
