# This file was generated by GoReleaser. DO NOT EDIT.
cask "oku" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "db820c390a8d246f9b97c1244083511841118100b011e3b8b85f3db511979206"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "736d96806796e3982c7f8d14131a44cb5181d13d0afa0ab750742c2712744151"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67e031fc98da23b0a6c6e91b662862ef2eacf57cc20a0aaecb4f2d5afd783bd2"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4662d9f0f7483080e4e3f3b852d09bd3031df6278f6bd1558b24679cdcc55329"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_linux_arm64.tar.gz"
    end
  end

  name "oku"
  desc "A terminal companion for Hardcover — track your reading from the CLI"
  homepage "https://github.com/Kameleon21/oku"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oku"

  # No zap stanza required

end
