# This file was generated by GoReleaser. DO NOT EDIT.
cask "oku" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "d4bfe8a3c0429c7213d7f2dde3a73419d45f2204c63bfa8831f8e85b079b3b2a"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "67a38ca3a76fb68b7ef5083f0fe6c6e4d639f8b40c333cc23a812e6a3487b690"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38ed08ae76b5a346e6eeb615391d6701c40cf570dbc4ae31589020cdc261124e"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ed10ff7ab83bd5d348d1dc20d49035c21b40667bf52d85d68945294afda10fb"
      url "https://github.com/Kameleon21/oku/releases/download/v#{version}/oku_linux_arm64.tar.gz"
    end
  end

  name "oku"
  desc "A terminal companion for Hardcover — track your reading from the CLI"
  homepage "https://github.com/Kameleon21/oku"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oku"

  # No zap stanza required

end
